### ISSUE TITLE
Bind variables do not passed from alias to script

### ISSUE THREAD

**Issue by nikitsky** [oracle/Oracle_DB_Tools#1]
I have faced an issue when tried to create an alias to save typing working with scripts. I looks like the bind variables are not passed to script if they are defined in alias. 
It's very simple to reproduce with the args.js as example.
Check how it should work:
```SQL
DEV>script args one two
0:args
1:one
2:two
```

create an alias:
```SQL
DEV>alias test_args=script args :p1 :p2;
DEV>alias list test_args
test_args
---------
script args :p1 :p2
```

and run the script though the alias:
```SQL
DEV>test_args one two

Command=test_args
0:args
1::p1
2::p2
```

**Comment by krisrice** [comment]
No need to pass binds as the APIs have full access to everything.  Try this:
binds = ctx.getVarMap();
numVar = binds.get('NUM_VAR');
value = numVar.getValue();
ctx.write("num_var = " + value + "\n");

**Comment by nikitsky** [comment]
Great, thank you Kris!

Can I get API description of ctx and sqlcl globals somewhere, please?

Regards,
Valentine

**Comment by krisrice** [comment]
It's coming just slowly.  There's a lot to cover so trying to come up with examples to match adding doc so it's clearer.

**Comment by nikitsky** [comment]
Thanks, examples are fine, will continue read your blog and the Oracle_DB_Tools repository. 

Thank you for really beautiful tool!

**Comment by krisrice** [comment]
You saw this I hope? https://github.com/oracle/Oracle_DB_Tools/blob/master/sqlcl/SCRIPTING.md

I'll be adding more and more to that.
